### ISSUE TITLE
npm install on the front-end directory results in error

### ISSUE THREAD

**Issue by absolutemadla8** [SimonHoiberg/saas-template#1]
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: serverless-aws-react-saas-front-end@undefined
npm ERR! Found: graphql@16.3.0
npm ERR! node_modules/graphql
npm ERR!   graphql@"^16.2.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer graphql@"^0.11.3 || ^0.12.3 || ^0.13.0 || ^14.0.0 || ^15.0.0" from apollo-link@1.2.14
npm ERR! node_modules/apollo-link
npm ERR!   apollo-link@"^1.2.14" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

**Comment by SimonHoiberg** [comment]
Hi, @absolutemadla8 

You can solve this by using `npm install --force` or `npm install --legacy-peer-deps`.
