### ISSUE TITLE
Apollo Client Error after login.

### ISSUE THREAD

**Issue by Viktrix8** [SimonHoiberg/saas-template#2]
Apollo client is apparently not working because I got everything right as I was following installation instructions I can create an account and in AWS Cognito I can see that created account.

I got following error: 
<img width="1438" alt="Snímka obrazovky 2022-07-28 o 21 39 16" src="https://user-images.githubusercontent.com/89099647/181623265-c870f6fd-6fcb-4dba-bda0-429d990961a8.png">

**Comment by SimonHoiberg** [comment]
Interesting.
Is it possible that you have a region mismatch somewhere?
E.g. Pulumi is setup to use `eu-west-2` but the client is configured to use `eu-west-1`?

**Comment by Viktrix8** [comment]
Thank You! Yes I've had AWS configured on eu-central-1 and pulumi on eu-west-1. Now it works fine.
