### ISSUE TITLE
Issue running npm run dev after all the configuring

### ISSUE THREAD

**Issue by sgr0691** [SimonHoiberg/saas-template#3]
I'm having an issue running the application locally by typing npm run dev it gives me an error message "sh: next: command not found" 
<img width="617" alt="error" src="https://user-images.githubusercontent.com/8444737/188061941-c1f141ce-961a-4af1-831c-958404056154.png">

**Comment by sgr0691** [comment]
Am I supposed to run npm run dev within the frontend folder or in the main directory?

**Comment by SimonHoiberg** [comment]
You are supposed to run this from within the front-end folder.
It's [this line right here](https://github.com/SimonHoiberg/saas-template/blob/main/front-end/package.json#L5).

Make sure you have Next set up properly.
See their [guide here](https://nextjs.org/docs).
